### ISSUE TITLE
Could you please share the dataset with us ？

### ISSUE THREAD

**Issue by melissamao** [MorrisXu-Driving/Video-Music_Cross-Modal_Retrival#1]
We are also trying to reproduce the paper, but the result is not good. However, it's hard for me to find the problems. I noticed that the result in the repo seems good, so could you please share the dataset used with us? Thanks so much.

**Comment by MorrisXu-Driving** [comment]
https://research.google.com/youtube8m/download.html you can try this youtube8m dataset, thanks.

**Comment by melissamao** [comment]
Thanks a lot! By the way, could you tell me the scale of the video number you used on this model？Thanks!



At 2022-07-02 22:11:41, "Morris Xu" ***@***.***> wrote:

https://research.google.com/youtube8m/download.html you can try this youtube8m dataset, thanks.

**Comment by MorrisXu-Driving** [comment]
We pretrained on the dataset I shared with you and then fine-tuned a dataset within the company for business usage. We use all the datasets in the youtube8m dataset and the dataset for fine-tuning cannot be disclosed because of company policy, thanks.
